Repository kunitoki/LuaBridge3, pull requests merged in 2023-03, with the labels that each got.

#52 Fix shared_ptr usage with inheritance
  Source/LuaBridge/detail/TypeTraits.h
  Tests/Source/Tests.cpp
Labels: bugfix

#57 Fix mutable references always bypassing library / user containers
  Source/LuaBridge/detail/Userdata.h
  Tests/Source/Tests.cpp
Labels: bugfix

#56 Improved enums bindings
  Manual.md
  README.md
  Source/CMakeLists.txt
  Source/LuaBridge/LuaBridge.h
  Source/LuaBridge/detail/CFunctions.h
  Source/LuaBridge/detail/Enum.h
  Source/LuaBridge/detail/LuaHelpers.h
  Source/LuaBridge/detail/LuaRef.h
  Source/LuaBridge/detail/Namespace.h
  Tests/CMakeLists.txt
  Tests/Source/ArrayTests.cpp
  Tests/Source/EnumTests.cpp
  Tests/Source/IssueTests.cpp
  Tests/Source/NamespaceTests.cpp
Labels: enhancement, feature

#72 Fix issue with overaligned UserdataValue
  Source/LuaBridge/detail/LuaHelpers.h
  Source/LuaBridge/detail/Userdata.h
  Tests/Source/ClassTests.cpp
Labels: bugfix

#73 Custom assert
  Source/LuaBridge/RefCountedObject.h
  Source/LuaBridge/detail/CFunctions.h
  Source/LuaBridge/detail/Config.h
  Source/LuaBridge/detail/Invoke.h
  Source/LuaBridge/detail/Iterator.h
  Source/LuaBridge/detail/LuaException.h
  Source/LuaBridge/detail/LuaHelpers.h
  Source/LuaBridge/detail/LuaRef.h
  Source/LuaBridge/detail/Namespace.h
  Source/LuaBridge/detail/Userdata.h
Labels: enhancement, minor

#69 Fix wrong error reported when passing no argument and a userdata is expected
  Source/LuaBridge/detail/Userdata.h
  Tests/Source/ClassTests.cpp
  Tests/Source/CoroutineTests.cpp
  Tests/Source/IssueTests.cpp
  Tests/Source/StackTests.cpp
Labels: bugfix

#79 Support for `__fastcall` function pointers
  CHANGES.md
  Distribution/LuaBridge/LuaBridge.h
  Source/LuaBridge/detail/FuncTraits.h
  Tests/Source/NamespaceTests.cpp
Labels: enhancement

#80 Enable testing only if LUABRIDGE_TESTING is ON
  CMakeLists.txt
Labels: bugfix

#78 Disallow metamethods in luabridge registered classes __index
  Source/LuaBridge/detail/CFunctions.h
  Tests/Source/ClassTests.cpp
Labels: bugfix
